-- Drop tables (children → parents)

DROP TABLE IF EXISTS GroupRequest CASCADE;
DROP TABLE IF EXISTS GroupMember CASCADE;
DROP TABLE IF EXISTS "Group" CASCADE;
DROP TABLE IF EXISTS Favorites CASCADE;
DROP TABLE IF EXISTS UserProfile CASCADE;
DROP TABLE IF EXISTS Listing CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- Drop ENUM types

DROP TYPE IF EXISTS group_status_enum CASCADE;
DROP TYPE IF EXISTS group_role_enum CASCADE;
DROP TYPE IF EXISTS request_status_enum CASCADE;

DROP TYPE IF EXISTS sleep_schedule_enum CASCADE;
DROP TYPE IF EXISTS cleanliness_enum CASCADE;
DROP TYPE IF EXISTS gender_enum CASCADE;